#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Checks prettier format
yarn prettier --check . || 
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn prettier:apply, add changes and try commit again.'; 
    false;
)

# Checks Next.js eslint rules
yarn lint || 
(
    echo '😤🏀👋😤 Next.js Eslint rules are not okay! 😤🏀👋😤 ' 
    false;
)

# Checks eslint rules
yarn eslint . --max-warnings 0 || 
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Checks typescript types
yarn tsc --pretty --noEmit || 
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'